name: Build and deploy Astro

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build Astro
        run: npm run build
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          RESEND_EMAIL: ${{ secrets.RESEND_EMAIL }}
          MY_EMAIL: ${{ secrets.MY_EMAIL }}

      - name: Connect to Tailscale
        uses: tailscale/github-action@v3
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Upload files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist,package.json,package-lock.json,ecosystem.config.cjs"
          target: ${{ secrets.APP_PATH }}

      - name: Restart app
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e

            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use 24.15.0

            echo "Node:"
            node -v

            echo "NPM:"
            npm -v

            echo "PM2:"
            pm2 -v

            cd ${{ secrets.APP_PATH }}

            # Crear archivo .env con variables de entorno
            cat > .env << 'EOF'
            RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}
            MY_EMAIL=${{ secrets.MY_EMAIL }}
            RESEND_EMAIL=${{ secrets.RESEND_EMAIL }}
            EOF

            npm ci --omit=dev --no-audit --no-fund

            pm2 restart portafolio-astro --update-env || pm2 start ecosystem.config.cjs

            pm2 save